using System;
using HealthScore.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HealthScore.Infrastructure.Migrations
{
    [DbContext(typeof(HealthScoreDbContext))]
    [Migration("20260710132000_AddProductMappings")]
    public partial class AddProductMappings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS `business_unit_controls` (
                    `Id` bigint NOT NULL AUTO_INCREMENT,
                    `BusinessUnit` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
                    `Vertical` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
                    `Product` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
                    `Scope` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
                    `UpdatedAt` datetime(6) NOT NULL,
                    `UpdatedBy` varchar(200) CHARACTER SET utf8mb4 NOT NULL,
                    CONSTRAINT `PK_business_unit_controls` PRIMARY KEY (`Id`)
                ) CHARACTER SET=utf8mb4;

                CREATE TABLE IF NOT EXISTS `product_mappings` (
                    `Id` bigint NOT NULL AUTO_INCREMENT,
                    `Vertical` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
                    `StandardProduct` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
                    `SourceSystem` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
                    `SourceValue` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
                    `CommercialProduct` varchar(255) CHARACTER SET utf8mb4 NULL,
                    `UpdatedAt` datetime(6) NOT NULL,
                    `UpdatedBy` varchar(200) CHARACTER SET utf8mb4 NOT NULL,
                    CONSTRAINT `PK_product_mappings` PRIMARY KEY (`Id`)
                ) CHARACTER SET=utf8mb4;

                DROP INDEX IF EXISTS `IX_business_unit_controls_BusinessUnit` ON `business_unit_controls`;
                CREATE INDEX IF NOT EXISTS `IX_business_unit_controls_BusinessUnit` ON `business_unit_controls` (`BusinessUnit`);
                CREATE UNIQUE INDEX IF NOT EXISTS `IX_business_unit_controls_BusinessUnit_Vertical_Product_Scope` ON `business_unit_controls` (`BusinessUnit`, `Vertical`, `Product`, `Scope`);
                CREATE INDEX IF NOT EXISTS `IX_business_unit_controls_Product` ON `business_unit_controls` (`Product`);
                CREATE INDEX IF NOT EXISTS `IX_business_unit_controls_Scope` ON `business_unit_controls` (`Scope`);
                CREATE INDEX IF NOT EXISTS `IX_business_unit_controls_Vertical` ON `business_unit_controls` (`Vertical`);
                CREATE UNIQUE INDEX IF NOT EXISTS `IX_product_mappings_SourceSystem_SourceValue` ON `product_mappings` (`SourceSystem`, `SourceValue`);
                CREATE INDEX IF NOT EXISTS `IX_product_mappings_StandardProduct` ON `product_mappings` (`StandardProduct`);
                CREATE INDEX IF NOT EXISTS `IX_product_mappings_Vertical` ON `product_mappings` (`Vertical`);
                """);

            migrationBuilder.Sql(
                """
                INSERT INTO `product_mappings` (`Vertical`, `StandardProduct`, `SourceSystem`, `SourceValue`, `CommercialProduct`, `UpdatedAt`, `UpdatedBy`) VALUES
                ('FARMA', 'BIG SISTEMAS', 'produto_padronizado', 'BIG SISTEMAS', 'LINX BIG FARMA', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'BIG SISTEMAS', 'produto_comercial', 'LINX BIG FARMA', 'LINX BIG FARMA', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'BIG SISTEMAS', 'produto_salesforce', 'LINX FARMA BIG', 'LINX BIG FARMA', UTC_TIMESTAMP(6), 'manual:alias-salesforce-produto'),
                ('FARMA', 'BIG SISTEMAS', 'unidade_negocio_produto', 'BIG SISTEMAS', 'LINX BIG FARMA', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'SOFTPHARMA', 'produto_padronizado', 'SOFTPHARMA', 'LINX SOFTPHARMA', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'SOFTPHARMA', 'produto_comercial', 'LINX SOFTPHARMA', 'LINX SOFTPHARMA', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'SOFTPHARMA', 'unidade_negocio_produto', 'SOFTPHARMA', 'LINX SOFTPHARMA', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'ITEC', 'produto_padronizado', 'ITEC', 'LINX ITEC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'ITEC', 'produto_comercial', 'LINX ITEC', 'LINX ITEC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'ITEC', 'unidade_negocio_produto', 'ITEC', 'LINX ITEC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'FARMA CLOUD', 'produto_padronizado', 'FARMA CLOUD', 'LINX FARMA CLOUD', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'FARMA CLOUD', 'produto_comercial', 'LINX FARMA CLOUD', 'LINX FARMA CLOUD', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA', 'FARMA CLOUD', 'unidade_negocio_produto', 'FARMA CLOUD', 'LINX FARMA CLOUD', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'DEGUST', 'produto_padronizado', 'DEGUST', 'LINX DEGUST', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'DEGUST', 'produto_comercial', 'LINX DEGUST', 'LINX DEGUST', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'DEGUST', 'unidade_negocio_produto', 'DEGUST', 'LINX DEGUST', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'MENEW', 'produto_padronizado', 'MENEW', 'LINX MENEW', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'MENEW', 'produto_comercial', 'LINX MENEW', 'LINX MENEW', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'MENEW', 'unidade_negocio_produto', 'MENEW', 'LINX MENEW', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'TASTE ONE', 'produto_padronizado', 'TASTE ONE', 'LINX TASTE ONE', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'TASTE ONE', 'produto_comercial', 'LINX TASTE ONE', 'LINX TASTE ONE', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'TASTE ONE', 'unidade_negocio_produto', 'TASTE ONE', 'LINX TASTE ONE', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'NEEMO', 'produto_padronizado', 'NEEMO', 'NEEMO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'NEEMO', 'produto_comercial', 'NEEMO', 'NEEMO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD', 'NEEMO', 'unidade_negocio_produto', 'NEEMO', 'NEEMO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'AUTOSYSTEM', 'produto_padronizado', 'AUTOSYSTEM', 'LINX AUTOSYSTEM', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'AUTOSYSTEM', 'produto_comercial', 'LINX AUTOSYSTEM', 'LINX AUTOSYSTEM', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'AUTOSYSTEM', 'unidade_negocio_produto', 'AUTOSYSTEM', 'LINX AUTOSYSTEM', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMSYS', 'produto_padronizado', 'EMSYS', 'LINX EMSYS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMSYS', 'produto_comercial', 'LINX EMSYS', 'LINX EMSYS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMSYS', 'unidade_negocio_produto', 'EMSYS', 'LINX EMSYS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO FÁCIL', 'produto_padronizado', 'POSTO FÁCIL', 'POSTO FÁCIL', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO FÁCIL', 'produto_padronizado_normalizado', 'POSTO FACIL', 'POSTO FÁCIL', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO FÁCIL', 'produto_comercial', 'POSTO FÁCIL', 'POSTO FÁCIL', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO FÁCIL', 'produto_comercial_normalizado', 'POSTO FACIL', 'POSTO FÁCIL', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO FÁCIL', 'unidade_negocio_produto', 'POSTO FÁCIL', 'POSTO FÁCIL', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO FÁCIL', 'unidade_negocio_produto_normalizado', 'POSTO FACIL', 'POSTO FÁCIL', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'SELLER', 'produto_padronizado', 'SELLER', 'LINX SELLER', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'SELLER', 'produto_comercial', 'LINX SELLER', 'LINX SELLER', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'SELLER', 'produto_salesforce', 'SELLER', 'LINX SELLER', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'SELLER', 'unidade_negocio_produto', 'SELLER', 'LINX SELLER', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO POP', 'produto_padronizado', 'POSTO POP', 'POSTO POP', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO POP', 'produto_comercial', 'POSTO POP', 'POSTO POP', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO POP', 'produto_salesforce', 'POSTO POP', 'POSTO POP', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'POSTO POP', 'unidade_negocio_produto', 'POSTO POP', 'POSTO POP', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMPÓRIO', 'produto_padronizado', 'EMPÓRIO', 'EMPÓRIO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMPÓRIO', 'produto_padronizado_normalizado', 'EMPORIO', 'EMPÓRIO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMPÓRIO', 'produto_comercial', 'EMPÓRIO', 'EMPÓRIO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMPÓRIO', 'produto_comercial_normalizado', 'EMPORIO', 'EMPÓRIO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS', 'EMPÓRIO', 'produto_salesforce', 'MPC', 'EMPÓRIO', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS', 'PAYHUB', 'produto_padronizado', 'PAYHUB', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS', 'PAYHUB', 'unidade_negocio_produto', 'PAYHUB', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS', 'MAR ABERTO', 'produto_padronizado', 'MAR ABERTO', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS', 'MAR ABERTO', 'unidade_negocio_produto', 'MAR ABERTO', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS', 'VERTICAIS', 'produto_padronizado', 'VERTICAIS', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS', 'VERTICAIS', 'unidade_negocio_produto', 'VERTICAIS', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL', 'MERCADAPP', 'produto_padronizado', 'MERCADAPP', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL', 'MERCADAPP', 'unidade_negocio_produto', 'MERCADAPP', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'SETA', 'produto_padronizado', 'SETA', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'SETA', 'unidade_negocio_produto', 'SETA', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'MICROVIX', 'produto_padronizado', 'MICROVIX', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'MICROVIX', 'unidade_negocio_produto', 'MICROVIX', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'RESHOP', 'produto_padronizado', 'RESHOP', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'RESHOP', 'unidade_negocio_produto', 'RESHOP', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'EASY LINX', 'produto_padronizado', 'EASY LINX', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'EASY LINX', 'unidade_negocio_produto', 'EASY LINX', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'MICROVIX PREMIER', 'produto_padronizado', 'MICROVIX PREMIER', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'MICROVIX PREMIER', 'unidade_negocio_produto', 'MICROVIX PREMIER', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'SETA SS', 'produto_padronizado', 'SETA SS', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL', 'SETA SS', 'unidade_negocio_produto', 'SETA SS', NULL, UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_')
                ON DUPLICATE KEY UPDATE
                    `Vertical` = VALUES(`Vertical`),
                    `StandardProduct` = VALUES(`StandardProduct`),
                    `CommercialProduct` = VALUES(`CommercialProduct`),
                    `UpdatedAt` = VALUES(`UpdatedAt`),
                    `UpdatedBy` = VALUES(`UpdatedBy`);
                """);

            migrationBuilder.Sql(
                """
                INSERT INTO `business_unit_controls` (`BusinessUnit`, `Vertical`, `Product`, `Scope`, `UpdatedAt`, `UpdatedBy`) VALUES
                ('ADESÃO - FARMA', 'FARMA', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ADESÃO - FOOD', 'FOOD', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ADESÃO - POSTOS', 'POSTOS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ADESÃO - RETAIL', 'RETAIL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ADMINISTRATIVO/FINANCEIRO', 'ADMFIN', 'ADMFIN', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('APOIO FRANQUIAS', 'OUTROS', 'OUTROS', 'FRANQUIAS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO - ADMINISTRATIVO/FINANCEIRO', 'AUTOMOTIVO', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO - LINX AUTOSHOP', 'AUTOMOTIVO', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO - LINX DMS / LINX DMS HPE / LINX DMS TOYOTA', 'AUTOMOTIVO', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO - LINX DMS BRAVOS', 'AUTOMOTIVO', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO - LINX SMART API', 'AUTOMOTIVO', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO - SISDIA', 'AUTOMOTIVO', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO-DEMANDAS INTERNAS APOLLO', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO-DEMANDAS INTERNAS AUTOSHOP', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('AUTOMOTIVO-DEMANDAS INTERNAS BRAVOS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('BACKOFFICE FOOD', 'FOOD', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('BRIDGE - CONECTIVIDADE', 'CONECTIVIDADE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('BRIDGE - FISCAL FLOW', 'CROSS', 'PAYHUB', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('BRIDGE - HUMANUS', 'LINX PEOPLE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('BRIDGE - HUMANUS CONSULTORIA', 'LINX PEOPLE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CALÇADOS - SETA DIGITAL', 'RETAIL', 'SETA', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CLOUD OPERATIONS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('COBRANÇA', 'ADMFIN', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CONECTIVIDADE - ADMINISTRATIVO/FINANCEIRO', 'CONECTIVIDADE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CORP - TOOLS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CORPORATIVO - FRANQUIAS E PARCEIROS LSP', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CORPORATIVO - PREMIER FRANQUIAS POSTOS', 'POSTOS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CORPORATIVO - XCENTER CONEC', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS - ADMINISTRATIVO/ FINANCEIRO', 'CROSS', 'ADMFIN', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS-MAR_ABERTO (ANTIGO PAYHUB)', 'CROSS', 'MAR ABERTO', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CROSS-VERTICAIS_LINX', 'CROSS', 'VERTICAIS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CS - NEEMO', 'FOOD', 'NEEMO', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('CS - POSTOS', 'POSTOS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DEGUST', 'FOOD', 'DEGUST', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DELIVERY CENTER - SHOPPING', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL - ADS', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL - ECOMMERCE - B2C', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL - ECOMMERCE - PARTNERS', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL - IMPULSE', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL - LINX COMMERCE', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL - LINX COMMERCE FAST', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('DIGITAL - LINX OMS', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('EMAIL DESCARTADO', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - ADMINISTRATIVO/FINANCEIRO', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - BIGRETAIL - WHITELABEL', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - DIGITAL - LINX COMMERCE', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - GESTÃO FRANQUIAS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - PAYHUB', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - RETENÇÃO', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - SERVIÇOS', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - STOREX', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE - STOREX HOME', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('ENTERPRISE – QUALITEAM', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - ADMINISTRATIVO/FINANCEIRO', 'FARMA', 'ADMFIN', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - ALÔ FRANQUIAS', 'FARMA', 'OUTROS', 'ALÔ PARCEIROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - BIG SISTEMAS', 'FARMA', 'BIG SISTEMAS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - CROSS', 'FARMA', 'OUTROS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - FARMA CLOUD', 'FARMA', 'FARMA CLOUD', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - IMPLANTAÇÕES', 'FARMA', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - ITEC', 'FARMA', 'ITEC', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - OPERA VENDAS', 'FARMA', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - RETENÇÃO', 'FARMA', 'OUTROS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FARMA - SOFTPHARMA', 'FARMA', 'SOFTPHARMA', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD - ADMINISTRATIVO/FINANCEIRO', 'FOOD', 'ADMFIN', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD - ALÔ FRANQUIAS', 'FOOD', 'OUTROS', 'ALÔ PARCEIROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD - BERCARIO', 'FOOD', 'OUTROS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD - EMSYS FOOD', 'FOOD', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD- Sala do Cliente - Food', 'FOOD', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-ADMFIN_RETENCAO', 'FOOD', 'ADMFIN', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-ADMFIN_RETENCAO', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-ALO_PARCEIRO', 'FOOD', 'OUTROS', 'ALÔ PARCEIROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-CS', 'FOOD', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-CS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-DEGUST', 'FOOD', 'DEGUST', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-MENEW', 'FOOD', 'MENEW', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-NEEMO', 'FOOD', 'NEEMO', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FOOD-TASTE_ONE', 'FOOD', 'TASTE ONE', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUEADOS - ENTERPRISE - MODA LINX', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUEADOS - POSTOS - POSTO FÁCIL', 'POSTOS', 'POSTO FÁCIL', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUEADOS FARMA - BIG SISTEMAS', 'FARMA', 'BIG SISTEMAS', 'FRANQUIAS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUEADOS POSTOS - AUTOSYSTEM', 'POSTOS', 'AUTOSYSTEM', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUEADOS POSTOS - EMSYS', 'POSTOS', 'EMSYS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUEADOS POSTOS SELLER E EMPÓRIO', 'POSTOS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUIA - PROSPECT - EMPORIO PRO', 'POSTOS', 'MPC', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('FRANQUIA - PROSPECT - SELLER', 'POSTOS', 'SELLER', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('Guardiões - Qualidade', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('LINX DIGITAL - LIDERES', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('LINX DIGITAL - QUALIDADE', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('LINX PROMO SUPORTE', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MELHORIAS - OFERTAS SHOPPING', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MELHORIAS - OFERTAS SHOPPING - MODA PREMIER', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MENEW', 'FOOD', 'MENEW', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MERCADAPP', 'DIGITAL', 'MERCADAPP', 'MERCADAPP', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MERCADO DE PROXIMIDADE - EMPÓRIO POP', 'POSTOS', 'MPC', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MERCADO DE PROXIMIDADE - EMPÓRIO PRÓ', 'POSTOS', 'MPC', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MILLENNIUM', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MILLENNIUM - SAAS', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MILLENNIUM - SERVIÇOS', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA - EASY LINX', 'RETAIL', 'EASY LINX', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA - LINX', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA - LINX - INTEGRAÇÕES', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA - LINX UX', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA - MICROVIX', 'RETAIL', 'MICROVIX', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA - MICROVIX WEB', 'RETAIL', 'MICROVIX', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA - RESHOP', 'RETAIL', 'RESHOP', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA PREMIER - LINX', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA PREMIER - LINX UX', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA PREMIER - MICROVIX', 'RETAIL', 'MICROVIX PREMIER', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('MODA PREMIER - MONITORIA', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('NEEMO', 'FOOD', 'NEEMO', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('NODIS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('OTICAS - MICROVIX', 'RETAIL', 'MICROVIX', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('PALIATIVO GO LIVE', 'FOOD', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('PAYHUB', 'CROSS', 'PAYHUB', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('PLUGG.TO', 'DIGITAL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('PORTO ALEGRE - PAY HUB', 'CROSS', 'PAYHUB', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('PORTO ALEGRE - PAY HUB - FARMA', 'CROSS', 'PAYHUB', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('PORTO ALEGRE - PAY HUB 2', 'CROSS', 'PAYHUB', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - ADMINISTRATIVO/FINANCEIRO', 'POSTOS', 'ADMFIN', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - AUTOSYSTEM', 'POSTOS', 'AUTOSYSTEM', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - BERÇARIO', 'POSTOS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - EMSYS', 'POSTOS', 'EMSYS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - POSTO FACIL', 'POSTOS', 'POSTO FÁCIL', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - POSTO POP', 'POSTOS', 'POSTO POP', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - SELLER', 'POSTOS', 'SELLER', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS - SERVIÇOS', 'POSTOS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('POSTOS- ALÔ FRANQUIAS', 'POSTOS', 'OUTROS', 'ALÔ PARCEIROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('PROJETO DEXTER', 'RETAIL', 'OUTROS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('QUALIDADE - CANAIS EXTERNOS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL - ADMINISTRATIVO/FINANCEIRO', 'RETAIL', 'ADMFIN', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL - RESHOP', 'RETAIL', 'RESHOP', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAIL- ALÔ FRANQUIAS', 'RETAIL', 'MICROVIX', 'ALÔ PARCEIROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETAL-SETA-CUSTOMIZAÇÃO', 'RETAIL', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETENÇÃO - LINX PAY', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('RETENÇÃO RC POSTOS', 'POSTOS', 'OUTROS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('SHOPPING - CROSS', 'OUTROS', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('SPECIAL SERVICE - SETA', 'RETAIL', 'SETA SS', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('TASTE ONE', 'FOOD', 'TASTE ONE', 'RC', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_'),
                ('VAREJO SERVICOS', 'ENTERPRISE', 'OUTROS', 'OUTROS', UTC_TIMESTAMP(6), 'xlsx:_de-para_produto_')
                ON DUPLICATE KEY UPDATE
                    `Vertical` = VALUES(`Vertical`),
                    `Product` = VALUES(`Product`),
                    `Scope` = VALUES(`Scope`),
                    `UpdatedAt` = VALUES(`UpdatedAt`),
                    `UpdatedBy` = VALUES(`UpdatedBy`);
                """);

            migrationBuilder.Sql(
                """
                INSERT INTO `product_portfolio_history` (`Product`, `ReferenceMonth`, `ActiveStores`, `UpdatedAt`, `UpdatedBy`) VALUES
                ('AUTOSYSTEM', DATE '2025-01-01', 6605, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-02-01', 6355, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-03-01', 6580, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-04-01', 6536, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-05-01', 6511, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-06-01', 6405, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-07-01', 5991, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-08-01', 5995, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-09-01', 5998, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-10-01', 5938, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-11-01', 5903, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2025-12-01', 5923, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2026-01-01', 5944, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2026-02-01', 5885, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2026-03-01', 5884, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2026-04-01', 5855, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2026-05-01', 5839, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2026-06-01', 5819, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('AUTOSYSTEM', DATE '2026-07-01', 5861, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-01-01', 5105, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-02-01', 5124, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-03-01', 5159, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-04-01', 5154, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-05-01', 5130, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-06-01', 5081, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-07-01', 4999, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-08-01', 4966, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-09-01', 5006, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-10-01', 4936, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-11-01', 4920, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2025-12-01', 4917, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2026-01-01', 4935, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2026-02-01', 4848, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2026-03-01', 4852, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2026-04-01', 4821, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2026-05-01', 4808, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2026-06-01', 4734, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('BIG SISTEMAS', DATE '2026-07-01', 4745, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-01-01', 6197, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-02-01', 5866, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-03-01', 6116, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-04-01', 6126, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-05-01', 6108, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-06-01', 6020, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-07-01', 5946, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-08-01', 5871, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-09-01', 5960, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-10-01', 5850, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-11-01', 5820, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2025-12-01', 5644, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2026-01-01', 5667, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2026-02-01', 5433, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2026-03-01', 5360, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2026-04-01', 5349, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2026-05-01', 4966, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2026-06-01', 4522, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('DEGUST', DATE '2026-07-01', 4530, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-01-01', 709, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-02-01', 698, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-03-01', 703, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-04-01', 695, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-05-01', 639, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-06-01', 667, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-07-01', 652, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-08-01', 648, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-09-01', 650, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-10-01', 634, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-11-01', 615, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2025-12-01', 615, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2026-01-01', 614, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2026-02-01', 599, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2026-03-01', 570, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2026-04-01', 567, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2026-05-01', 564, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2026-06-01', 560, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EASY LINX', DATE '2026-07-01', 560, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMPÓRIO', DATE '2025-01-01', 1925, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-02-01', 1873, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-03-01', 1795, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-04-01', 1806, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-05-01', 1910, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-06-01', 1882, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-07-01', 1733, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-08-01', 1556, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-09-01', 1577, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-10-01', 1462, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-11-01', 1466, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2025-12-01', 1399, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2026-01-01', 1470, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2026-02-01', 1449, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2026-03-01', 1398, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2026-04-01', 1391, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2026-05-01', 1356, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2026-06-01', 1333, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMPÓRIO', DATE '2026-07-01', 1333, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('EMSYS', DATE '2025-01-01', 2872, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-02-01', 2553, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-03-01', 2767, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-04-01', 2824, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-05-01', 2926, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-06-01', 2922, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-07-01', 2865, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-08-01', 2893, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-09-01', 2899, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-10-01', 2887, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-11-01', 2926, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2025-12-01', 2945, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2026-01-01', 2973, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2026-02-01', 2975, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2026-03-01', 2974, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2026-04-01', 2970, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2026-05-01', 2945, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2026-06-01', 2941, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('EMSYS', DATE '2026-07-01', 2974, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-01-01', 58, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-02-01', 42, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-03-01', 40, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-04-01', 6, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-05-01', 4, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-06-01', 3, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-07-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-08-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-09-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-10-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-11-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2025-12-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2026-01-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2026-02-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2026-03-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2026-04-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2026-05-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2026-06-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('FARMA CLOUD', DATE '2026-07-01', 2, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-01-01', 1340, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-02-01', 1487, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-03-01', 1498, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-04-01', 1487, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-05-01', 1485, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-06-01', 1486, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-07-01', 1437, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-08-01', 1437, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-09-01', 1442, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-10-01', 1462, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-11-01', 1470, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2025-12-01', 1392, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2026-01-01', 1416, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2026-02-01', 1426, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2026-03-01', 1434, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2026-04-01', 1437, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2026-05-01', 1411, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2026-06-01', 1403, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('ITEC', DATE '2026-07-01', 1404, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-01-01', 3419, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-02-01', 3371, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-03-01', 3426, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-04-01', 3387, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-05-01', 3331, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-06-01', 3298, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-07-01', 3137, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-08-01', 3067, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-09-01', 3125, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-10-01', 2996, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-11-01', 2974, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2025-12-01', 2882, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2026-01-01', 2892, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2026-02-01', 2765, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2026-03-01', 2720, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2026-04-01', 2645, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2026-05-01', 2602, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2026-06-01', 2528, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MENEW', DATE '2026-07-01', 2530, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-01-01', 15051, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-02-01', 15039, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-03-01', 15304, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-04-01', 15324, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-05-01', 15245, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-06-01', 15126, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-07-01', 14964, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-08-01', 14982, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-09-01', 15287, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-10-01', 15269, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-11-01', 15429, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2025-12-01', 15333, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2026-01-01', 15447, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2026-02-01', 15172, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2026-03-01', 15279, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2026-04-01', 15184, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2026-05-01', 15189, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2026-06-01', 15095, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('MICROVIX', DATE '2026-07-01', 15116, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-01-01', 3255, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-02-01', 3130, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-03-01', 3154, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-04-01', 3052, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-05-01', 2929, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-06-01', 2892, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-07-01', 2752, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-08-01', 2606, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-09-01', 2636, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-10-01', 2486, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-11-01', 2410, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2025-12-01', 2331, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2026-01-01', 2315, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2026-02-01', 2153, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2026-03-01', 2111, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2026-04-01', 2074, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2026-05-01', 1987, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2026-06-01', 1906, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('NEEMO', DATE '2026-07-01', 1907, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-01-01', 1275, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-02-01', 1226, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-03-01', 1230, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-04-01', 1224, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-05-01', 1214, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-06-01', 1204, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-07-01', 1174, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-08-01', 1176, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-09-01', 1187, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-10-01', 1162, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-11-01', 1138, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2025-12-01', 1117, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2026-01-01', 1122, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2026-02-01', 1089, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2026-03-01', 1081, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2026-04-01', 1062, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2026-05-01', 1047, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2026-06-01', 1030, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('POSTO FÁCIL', DATE '2026-07-01', 1034, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SELLER', DATE '2025-01-01', 1925, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-02-01', 1873, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-03-01', 1795, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-04-01', 1806, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-05-01', 1910, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-06-01', 1882, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-07-01', 1733, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-08-01', 1556, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-09-01', 1577, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-10-01', 1462, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-11-01', 1466, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2025-12-01', 1399, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2026-01-01', 1470, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2026-02-01', 1449, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2026-03-01', 1398, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2026-04-01', 1391, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2026-05-01', 1356, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2026-06-01', 1333, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SELLER', DATE '2026-07-01', 1333, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas:SELLER/MPC'),
                ('SETA', DATE '2025-01-01', 4221, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-02-01', 3856, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-03-01', 4335, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-04-01', 4352, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-05-01', 4364, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-06-01', 4360, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-07-01', 4357, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-08-01', 4357, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-09-01', 4406, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-10-01', 4421, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-11-01', 4472, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2025-12-01', 4472, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2026-01-01', 4460, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2026-02-01', 4413, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2026-03-01', 4470, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2026-04-01', 4484, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2026-05-01', 4533, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2026-06-01', 4528, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SETA', DATE '2026-07-01', 4533, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-01-01', 1255, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-02-01', 1239, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-03-01', 1243, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-04-01', 1210, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-05-01', 1167, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-06-01', 1158, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-07-01', 1128, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-08-01', 1103, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-09-01', 1108, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-10-01', 1078, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-11-01', 1056, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2025-12-01', 1039, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2026-01-01', 1039, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2026-02-01', 1012, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2026-03-01', 1005, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2026-04-01', 981, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2026-05-01', 970, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2026-06-01', 963, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('SOFTPHARMA', DATE '2026-07-01', 961, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-01-01', 97, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-02-01', 103, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-03-01', 109, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-04-01', 116, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-05-01', 139, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-06-01', 162, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-07-01', 180, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-08-01', 207, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-09-01', 225, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-10-01', 225, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-11-01', 225, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2025-12-01', 225, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2026-01-01', 225, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2026-02-01', 331, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2026-03-01', 346, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2026-04-01', 346, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2026-05-01', 422, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas'),
                ('TASTE ONE', DATE '2026-06-01', 421, UTC_TIMESTAMP(6), 'csv:qtde_lojas_ativas')
                ON DUPLICATE KEY UPDATE
                    `ActiveStores` = VALUES(`ActiveStores`),
                    `UpdatedAt` = VALUES(`UpdatedAt`),
                    `UpdatedBy` = VALUES(`UpdatedBy`);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DELETE FROM `product_portfolio_history`
                WHERE `UpdatedBy` LIKE 'csv:qtde_lojas_ativas%';
                """);
            migrationBuilder.DropTable(name: "product_mappings");
            migrationBuilder.DropTable(name: "business_unit_controls");
        }
    }
}
